# Generated by Django 3.2.3 on 2021-06-01 16:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='messege',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='messege_html',
            new_name='message_html',
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('user', 'message')},
        ),
    ]
