# Generated by Django 3.2.3 on 2021-06-04 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_subcategory_main_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_subcategory', to='blog.category'),
        ),
    ]
