# Generated by Django 3.2.3 on 2021-06-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug_category',
            field=models.SlugField(allow_unicode=True, default='', editable=False, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug_subcategory',
            field=models.SlugField(allow_unicode=True, default='', editable=False, max_length=200, unique=True),
        ),
    ]
