# Generated by Django 3.2.3 on 2021-06-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210607_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug_category',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='slug_subcategory',
            new_name='slug',
        ),
    ]
